### ISSUE TITLE
Use mathematical terms for Set operations

### ISSUE THREAD

**Issue by j201** [calvinmetcalf/set.up#3]
I just wanted to point out that the names used for set operations here don't match up with the commonly used names for them.
- The union of two sets has the elements that are present in either or both of the sets. You have it as `Set.prototype.merge`
- The intersection of two sets has only the elements that are present in both. You have this as `Set.prototype.union`
- The complement of two sets has only the elements present in the first but not in the second. You don't have any corresponding function.
- The symmetric difference of two sets has the elements that are present in either of the sets but not both. You have this as `Set.prototype.xor`

The operation names are kind of long, so you'd probably want to abbreviate them, but I think consistently using the mathematical terms would make this library easier to use for those familiar with set theory.

[Reference](https://en.wikipedia.org/wiki/Set_%28mathematics%29#Basic_operations)

**Comment by calvinmetcalf** [comment]
I can have union and merge point to the same thing and have symmetricDifference point to xor and have intersection point to what is now union, and then add complement, how does that sound?
