### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by benjamingr** [calvinmetcalf/set.up#5]
Hey, are you going to pursue this as a TC proposal?

**Comment by calvinmetcalf** [comment]
I hadn't really planned it on a couple grounds
- sets are still pretty new so people are still figuring out what's good to do with them, it would be a good idea from my perspective, to let the ecosystem figure out what kinds of functions are helpful before we try to standardize anything
- the ability to subclass builtins makes the need to do this less pressing

**Comment by benjamingr** [comment]
Thanks
